# Generated by Django 3.2.4 on 2021-06-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_diarista_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarista',
            name='bairro',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='diarista',
            name='logradouro',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
